// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckFFmpeg():Promise<boolean>;

export function ClearHistory():Promise<number>;

export function ClearVideoInfoCache():Promise<number>;

export function ConvertFolder(arg1:main.NCMConvertRequest):Promise<main.NCMConvertResponse>;

export function DeleteHistory(arg1:string):Promise<void>;

export function GetHistory():Promise<Array<main.HistoryRecord>>;

export function HasActiveTasks():Promise<boolean>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenFilesDialog(arg1:string,arg2:string,arg3:string):Promise<Array<string>>;

export function OpenInFileManager(arg1:string):Promise<void>;

export function ParseVideoInfo(arg1:main.ParseInfoRequest):Promise<main.VideoInfo>;

export function StartDownload(arg1:main.DownloadRequest):Promise<main.JobInfo>;

export function StartM3U8(arg1:main.M3U8Request):Promise<main.JobInfo>;

export function StartMagnet(arg1:main.MagnetRequest):Promise<main.JobInfo>;

export function StopDownload(arg1:string):Promise<void>;
