// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckFFmpeg() {
  return window['go']['main']['App']['CheckFFmpeg']();
}

export function ClearVideoInfoCache() {
  return window['go']['main']['App']['ClearVideoInfoCache']();
}

export function ConvertFolder(arg1) {
  return window['go']['main']['App']['ConvertFolder'](arg1);
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function OpenFilesDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFilesDialog'](arg1, arg2, arg3);
}

export function OpenInFileManager(arg1) {
  return window['go']['main']['App']['OpenInFileManager'](arg1);
}

export function ParseVideoInfo(arg1) {
  return window['go']['main']['App']['ParseVideoInfo'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function StartM3U8(arg1) {
  return window['go']['main']['App']['StartM3U8'](arg1);
}

export function StartMagnet(arg1) {
  return window['go']['main']['App']['StartMagnet'](arg1);
}

export function StopDownload() {
  return window['go']['main']['App']['StopDownload']();
}
